### ISSUE TITLE
<Suggestion> Make the damage values more accurate to 1.8, and add option to have punching sound and sweeping attack sound.

### ISSUE THREAD

**Issue by DanielMC101** [rizecookey/CombatEdit#12]
So I'm using this mod called Legacy4J, which aims to adapt all console editions features to Java Edition even has native controller support, but doesn't have the console edition combat mode, so I decided to use this mod to solve that, but the problem is, the damage values are not accurate. and completely gets rid of punching sound.

The hoes should all do 0 damage
All the weapons/tools except hoes should do -1 damage values then it is right now to make it accurate to Java Edition 1.8/ Console Edition

The trident's damage value on Bedrock/Console Edition is 8

**Comment by rizecookey** [comment]
I've adjusted all damage values to match the ones in Bedrock Edition with release [1.6.4](https://github.com/rizecookey/CombatEdit/releases/tag/v1.6.4). That also means that hoes will deal the same amount of damage as pickaxes for now.
I've had numerous request to change the damage of some tools to different values, but since there are a lot of different opinions on what exactly they should be, it's not easy to make a compromise - which is why I am planning to make all damage values (and in fact, all attribute modifiers) for all items **completely customizable** with a config eventually (I've done some work in the latest release to make that easier already). As I am usually pretty busy with university though, I **can't really make any promises** as to _when_ that will happen.

As for your second point - the damage values set in the mod were correct, however there might be some confusion regarding the display of those values. The new green tooltip for damage (and attack speed) values introduced in 1.9 for items that have not been modified manually shows the **total damage dealt with that item** in hand. The old blue tooltips used in other cases, pre-1.9 versions and Bedrock as well as Console Editions, however, _only_ show the **additional damage added by that tool/weapon** - meaning that if the tooltip shows +7 damage, you will actually deal 8 damage in total (7 + 1 for the default damage dealt by your hand/non-tool items). CombatEdit uses the new green tooltips in singleplayer and the old blue ones in multiplayer apart from the creative inventory (which shows incorrect damage values in multiplayer because of limitations with the vanilla client) for technical reasons that have to do with how attribute modifiers are handled by the client.

Regarding the attacking sounds - those have mostly been disabled because they otherwise result in sound spam when spam-clicking on an entity (they play regardless if that entity has taken any damage or not). I plan on looking into some other ways for handling them and making them configurable with a future update as well.

**Comment by rizecookey** [comment]
Options for changing the damage values as well as disabling and enabling different attack sounds have been added in release [2.0.0](https://github.com/rizecookey/CombatEdit/releases/tag/v2.0.0%2B1.20.6).

**Comment by DanielMC101** [comment]
@rizecookey I'm bit surprised you haven't ported to 1.21 yet, any plans for that?
