### ISSUE TITLE
<Suggestion> 1.21 port

### ISSUE THREAD

**Issue by DanielMC101** [rizecookey/CombatEdit#16]
hoping you'll port this to 1.21 some day because I really would love to play Legacy4J mod alongside with this

**Comment by DanielMC101** [comment]
really hope this happens, cuz 1.21 port of Legacy4J is coming very soon

**Comment by DanielMC101** [comment]
@rizecookey oh okay that's good

**Comment by DanielMC101** [comment]
@rizecookey so btw, with the current added configuration, is it now possible to make the tools/weapons show attack damage without including player's base damage?

**Comment by rizecookey** [comment]
I've finally ported the mod to 1.21.1 with release [2.0.2](https://github.com/rizecookey/CombatEdit/releases/tag/v2.0.2%2B1.21.1). Sorry it took so long - I ended up rewriting large parts of the mod since 2.0.0 as I noticed some issues.
As for the tooltip option - please open another issue for that one, I will consider adding that feature in the future.
