### ISSUE TITLE
<Suggestion> Add an option to config to make the tooltips look like from Legacy Console Edition.

### ISSUE THREAD

**Issue by DanielMC101** [rizecookey/CombatEdit#20]
I honestly really appreciate for creating this mod, and I think it would be very wonderful if you were to add this option.

I'm actually a leader of playtesting for Legacy4J mod, and I have a love, dedication for Legacy Console Edition, the creator WilyICaro of Legacy4J unfortunately doesn't really plan on adding the 1.8 combat mode along with the LCE style tooltips anytime soon, so adding this option would be a huge help and I can see this mod becoming a part of re-console modpack again.

So in Legacy Console Edition, the way that tooltips displays is that it has a .0, and doesn't really show "When on main hand", "When on body", etc, and when the damage value is 0, the text would be gray.

https://github.com/user-attachments/assets/11ac492f-3264-4007-9369-73707eadeb64

https://github.com/user-attachments/assets/6ce21ac1-057d-4d7d-8cd4-cb1c4742d0ff

**Comment by Cixon** [comment]
upvoted but also, what if CombatEdit just disables their tooltip mixins if `Legacy 4J` is detected? this would be best I feel…

like a simple `disabled = FabricLoader.getInstance().isModLoaded("legacy")`

**Comment by rizecookey** [comment]
I've thought a bit about adding this, but after fiddling around a bit, I've decided on not adding it because
- unlike in legacy console editions, items can have different modifiers for different slots in Java Edition, which means a clarification of which modifiers apply to which slots is justified
- the effort is not proportional to the usefulness of the feature
- it's not really part of this mod's goal.

**Comment by DanielMC101** [comment]
@rizecookey oh okay, but can you at least make it like display with a .0?
