### ISSUE TITLE
Gamerule for 1.8 pvp on/off

### ISSUE THREAD

**Issue by TechPro424** [rizecookey/CombatEdit#6]
Suggestion: Add a `/gamerule 1.8pvp` command that can be made `true` or `false` to enable and disable 1.8 pvp
default can be `true`

**Comment by rizecookey** [comment]
The current way the mod operates is that it modifies damage and cooldown values on startup, therefore making this impossible without a rewrite of the entire mod. Making a gamerule modify these on-the-fly would be a more difficult job as the Minecraft code isn't layed out for that, and my focus currently is to maintain the mod and update it for newer versions rather than adding new features.
